# Prácticas básicas con Python

#### Ejercicio 00. Declaración de Variables

Define las siguientes variables con valores que tú elijas:

- Una variable que almacene tu nombre (texto).
- Una variable que almacene tu edad (número entero).
- Una variable que indique si te gusta la programación (verdadero o falso).
- Una variable que almacene tu calificación promedio (número decimal).

In [7]:
# Declara aquí tus variables.

#Ejemplo
saludo = "Hola mundo" 
nombre = "Daniel Alberto"
Edad = 36
Programacion = True
Calificacion = 10

- Crea una lista con tus cinco números favoritos e imprimelo.

In [8]:
# Lista de números favoritos
numeros_favoritos = [1,2,3,4,5,6]

- Crea un diccionario que guarde la información de un estudiante e imprimelo:

        - Nombre
        - Edad
        - Calificación final

In [9]:
# Diccionario del estudiante
nuevo_diccionario = {
    "nombre" : "Daniel Alberto",
    "Edad" : 36,
    "Calificacion" :10
}

#### Ejercicio 01. Análisis de datos básico con estructuras nativas de python.
Crea una lista con las calificaciones de 5 estudiantes: [8.5, 9.2, 7.8, 8.9, 10].

- Calcula el promedio de las calificaciones.

In [ ]:
# Código
calificaciones = [8.5, 9.2, 7.8, 8.9, 10]
promedio = sum(calificaciones) / len (calificaciones)
print(promedio)

8.879999999999999

- Encuentra la calificación más alta y la más baja.

In [5]:
# Código
calificaciones = [8.5, 9.2, 7.8, 8.9, 10]
calificacion_mas_baja= min(calificaciones)
calificacion_mas_alta= max(calificaciones)
print("Calificacion más baja: ",calificacion_mas_baja)
print("Calificacion más alta: ",calificacion_mas_alta)

Calificacion más baja:  7.8
Calificacion más alta:  10

# Limpieza de bienes raíces con Pandas para un análisis eficiente 

Este es un conjunto de datos (dataset) reales que fue descargado usando técnicas de web scraping. La data contiene registros de **Fotocasa**, el cual es uno de los sitios más populares de bienes raíces en España. Por favor no hagas esto (web scraping) a no ser que sea para propósitos académicos.

El dataset fue descargado hace algunos años por Henry Navarro y en ningún caso se obtuvo beneficio económico de ello.

Contiene miles de datos de casas reales publicadas en la web www.fotocasa.com. Tu objetivo es extraer tanta información como sea posible con el conocimiento que tienes hasta ahora de ciencia de datos.

¡Comencemos!




- Primero leamos y exploraremos el dataset

In [1]:
import pandas as pd

# Leer el archivo CSV
ds = pd.read_csv('assets/real_estate.csv', sep=';') # Este archivo CSV contiene puntos y comas en lugar de comas como separadores
ds # mostramos todo

,Unnamed: 0,id_realEstates,isNew,realEstate_name,phone_realEstate,url_inmueble,rooms,bathrooms,surface,price,...,level4Id,level5Id,level6Id,level7Id,level8Id,accuracy,latitude,longitude,zipCode,customZone
0,1,153771986,False,ferrari 57 inmobiliaria,912177526.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,103.0,195000,...,0,0,0,0,0,0,"40,2948276786438","-3,44402412135624",NaN,NaN
1,2,153867863,False,tecnocasa fuenlabrada ferrocarril,916358736.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,NaN,89000,...,0,0,0,0,0,1,"40,28674","-3,79351",NaN,NaN
2,3,153430440,False,look find boadilla,916350408.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,2.0,99.0,390000,...,0,0,0,0,0,0,"40,4115646786438","-3,90662252135624",NaN,NaN
3,4,152776331,False,tecnocasa fuenlabrada ferrocarril,916358736.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,86.0,89000,...,0,0,0,0,0,0,"40,2853785786438","-3,79508142135624",NaN,NaN
4,5,153180188,False,ferrari 57 inmobiliaria,912177526.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,2.0,106.0,172000,...,0,0,0,0,0,0,"40,2998774864376","-3,45226301356237",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15330,15331,153901377,False,infocasa consulting,911360461.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,1.0,96.0,259470,...,0,0,0,0,0,0,"40,45416","-3,70286",NaN,NaN
15331,15332,150394373,False,inmobiliaria pulpon,912788039.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,150.0,165000,...,0,0,0,0,0,0,"40,36652","-3,48951",NaN,NaN
15332,15333,153901397,False,tecnocasa torrelodones,912780348.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,4.0,2.0,175.0,495000,...,0,0,0,0,0,0,"40,57444","-3,92124",NaN,NaN
15333,15334,152607440,False,inmobiliaria pulpon,912788039.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,101.0,195000,...,0,0,0,0,0,0,"40,36967","-3,48105",NaN,NaN
15334,15335,153901356,False,infocasa consulting,911360461.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,152.0,765000,...,0,0,0,0,0,0,"40,45773","-3,69068",NaN,NaN

- Muestra las primeras filas del archivo CSV

In [2]:
# Mostrar las primeras filas
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';') # Este archivo CSV contiene puntos y comas en lugar de comas como separadores
ds.head(15)

,Unnamed: 0,id_realEstates,isNew,realEstate_name,phone_realEstate,url_inmueble,rooms,bathrooms,surface,price,...,level4Id,level5Id,level6Id,level7Id,level8Id,accuracy,latitude,longitude,zipCode,customZone
0,1,153771986,False,ferrari 57 inmobiliaria,912177526.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,103.0,195000,...,0,0,0,0,0,0,"40,2948276786438","-3,44402412135624",NaN,NaN
1,2,153867863,False,tecnocasa fuenlabrada ferrocarril,916358736.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,NaN,89000,...,0,0,0,0,0,1,"40,28674","-3,79351",NaN,NaN
2,3,153430440,False,look find boadilla,916350408.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,2.0,99.0,390000,...,0,0,0,0,0,0,"40,4115646786438","-3,90662252135624",NaN,NaN
3,4,152776331,False,tecnocasa fuenlabrada ferrocarril,916358736.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,86.0,89000,...,0,0,0,0,0,0,"40,2853785786438","-3,79508142135624",NaN,NaN
4,5,153180188,False,ferrari 57 inmobiliaria,912177526.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,2.0,106.0,172000,...,0,0,0,0,0,0,"40,2998774864376","-3,45226301356237",NaN,NaN
5,6,153934794,False,expimad,912780412.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,1.0,70.0,315000,...,0,0,0,0,0,0,"40,53391","-3,89445",NaN,NaN
6,7,153848236,False,expimad,912780412.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,2.0,145.0,430000,...,0,0,0,0,0,0,"40,5105842135624","-3,89436578643763",NaN,NaN
7,8,153482331,False,expimad,912780412.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,1.0,95.0,275000,...,0,0,0,0,0,0,"40,53294","-3,89898",NaN,NaN
8,9,153885351,False,expimad,912780412.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,4.0,3.0,277.0,445000,...,0,0,0,0,0,0,"40,5363057864376","-3,89294421356237",NaN,NaN
9,10,153215459,False,modesta,NaN,https://www.fotocasa.es/es/comprar/vivienda/ma...,4.0,2.0,129.0,350000,...,0,0,0,0,0,0,"40,37502","-3,74391",NaN,NaN
10,11,153985475,False,inmobiliaria nuevo leganes,918007516.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,3.0,1.0,86.0,98000,...,0,0,0,0,0,0,"40,3811257864376","-3,73996578643763",NaN,NaN
11,12,151795159,False,gm house,916357589.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,4.0,3.0,246.0,540000,...,0,0,0,0,0,0,"40,3667178869885","-3,92641067504883",NaN,NaN
12,13,153140254,False,alia consulting inmobiliario sl,912789762.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,2.0,2.0,67.0,179900,...,0,0,0,0,0,0,"40,25545","-3,6995",NaN,NaN
13,14,151911172,False,alia consulting inmobiliario sl,912789762.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,1.0,1.0,50.0,142900,...,0,0,0,0,0,0,"40,19025","-3,68717",NaN,NaN
14,15,153149473,False,tecnocasa navalcarnero,911790965.0,https://www.fotocasa.es/es/comprar/vivienda/ma...,4.0,2.0,270.0,229900,...,0,0,0,0,0,0,"40,2838","-4,00753",NaN,NaN

Perfecto, esto fue una pequeña practica. ¡Ahora empecemos con los verdaderos ejercicios!

#### Ejercicio 01. ¿Cuál es la casa más cara en todo el dataset? (★☆☆)

Imprime la dirección y el precio de la casa seleccionada. Por ejemplo:

`La casa con dirección en Calle del Prado, Nº20 es la más cara y su precio es de 5000000 USD`

In [9]:
# TODO
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';') 
maximo = ds['price'].max()
id_maximo = ds['price'].idxmax()
datos = ds[ds['price']==maximo]
direccion = ds.loc[id_maximo, 'address']
print("la casa más cara esta en ",direccion, " y su precio es ",maximo)

la casa más cara esta en  El Escorial  y su precio es  8500000

#### Ejercicio 02. ¿Cuál es la casa más barata del dataset? (★☆☆)

Este ejercicio es similar al ejercicio anterior, solo que ahora buscamos la casa con el precio más bajo. Recuerda imprimir la dirección y el precio de la casa seleccionada. Por ejemplo:

`La casa con dirección en Calle Alcalá, Nº58 es la más barata y su precio es de 12000 USD`

In [7]:
# TODO
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';') 
casas_convalor_mayor0 = ds[ds['price']>0]
#casas_convalor_mayor0
minimo = casas_convalor_mayor0['price'].min()
id_minimo = casas_convalor_mayor0['price'].idxmin()
datos = casas_convalor_mayor0[casas_convalor_mayor0['price']==minimo]
direccion = ds.loc[id_minimo, 'address']
print("la casa más barata esta en ",direccion, " y su precio es ",minimo)

la casa más barata esta en  Berlin, Coslada  y su precio es  600

#### Ejercicio 03. ¿Cuál es la casa más grande y la más pequeña del dataset? (★☆☆)

Imprime la dirección y el área de las casas seleccionadas. Por ejemplo:

`La casa más grande está ubicada en Calle Gran Vía, Nº38 y su superficie es de 5000 metros`

`La casa más pequeña está ubicada en Calle Mayor, Nº12 y su superficie es de 200 metros`

Este ejercicio es similar al anterior, pero buscamos las casas más grandes y pequeñas en base a su superficie.

In [8]:
# TODO
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';') 
minimo = ds['surface'].min()
id_minimo = ds['surface'].idxmin()
datosmin = ds[ds['surface']==minimo]

maximo = ds['surface'].max()
id_maximo = ds['surface'].idxmax()
datosmax = ds[ds['surface']==maximo]

#print(datosmax)
direccionmin = ds.loc[id_minimo, 'realEstate_name']
direccionmax = ds.loc[id_maximo, 'realEstate_name']
print("la casa con menor superficie esta ubicada en ",direccionmin, " y su superficie es  ",minimo)
print("la casa con mayor superficie esta ubicada en ",direccionmax, " y su superficie es  ",maximo)

la casa con menor superficie esta ubicada en  toledo21  y su superficie es   15.0
la casa con mayor superficie esta ubicada en  habitarium inmobiliaria  y su superficie es   249000.0

#### Ejercicio 04. ¿Cuantas poblaciones contiene el dataset? (★☆☆)

Cuenta el número de poblaciones únicas en la columna 'level5' e imprime el nombre de las poblaciones separadas por coma. Por ejemplo:

`> print(populations)`

`population1, population2, population3, ...`

In [1]:
# TODO
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';') 
print(f'Cantidad de poblaciones únicas en level5: {len(ds.level5.unique())}')
print(list(ds.level5.unique()))

Cantidad de poblaciones únicas en level5: 168
['Arganda del Rey', 'Fuenlabrada', 'Boadilla del Monte', 'Las Rozas de Madrid', ' Madrid Capital', 'Villaviciosa de Odón', 'Pinto', 'Valdemoro', 'Navalcarnero', 'Pozuelo de Alarcón', 'Torrejón de Ardoz', 'Navalagamella', 'San Sebastián de los Reyes', 'Rivas-vaciamadrid', 'Alpedrete', 'Móstoles', 'San Fernando de Henares', 'Coslada', 'Becerril de la Sierra', 'Alcalá de Henares', 'Chinchón', 'Parla', 'Alcorcón', 'El Escorial', 'Leganés', 'Pedrezuela', 'Majadahonda', 'Villanueva de la Cañada', 'Villanueva del Pardillo', 'Torrelodones', 'Moralzarzal', 'Mejorada del Campo', 'Aranjuez', 'Corpa', 'Getafe', 'Velilla de San Antonio', 'Sevilla la Nueva', 'San Martín de la Vega', 'Villalbilla', 'Collado Villalba', 'Alcobendas', 'El Molar (Madrid)', 'Moraleja de Enmedio', 'Algete', 'Campo Real', 'Torrejón de la Calzada', 'Colmenar Viejo', 'Valdemorillo', 'Fuente El Saz de Jarama', 'Tres Cantos', 'Arroyomolinos (Madrid)', 'Griñón', 'Paracuellos de Jarama', 'Guadarrama', 'Titulcia', 'Galapagar', 'Collado Mediano', 'Los Molinos', 'San Lorenzo de El Escorial', 'Loeches', 'San Martín de Valdeiglesias', 'Navas del Rey', 'Bustarviejo', 'Manzanares El Real', 'Carabaña', 'Casarrubuelos', 'Cercedilla', 'Fresnedillas de la Oliva', 'Valdemaqueda', 'Robledo de Chavela', 'Miraflores de la Sierra', 'Humanes de Madrid', 'Valdetorres de Jarama', 'San Agustín del Guadalix', 'Ciempozuelos', 'Camarma de Esteruelas', 'Torres de la Alameda', 'Talamanca de Jarama', 'El Atazar', 'Hoyo de Manzanares', 'El Boalo - Cerceda – Mataelpino', 'El Álamo', 'Valdilecha', 'Valdeolmos-Alalpardo', 'Guadalix de la Sierra', 'Belmonte de Tajo', 'El Vellón', 'Brunete', 'Redueña', 'Morata de Tajuña', 'Tielmes', 'Gargantilla del Lozoya', 'Meco', 'Venturada', 'Quijorna', 'Cenicientos', 'Torrejón de Velasco', 'Navacerrada', 'Santa María de la Alameda', 'Orusco de Tajuña', 'Daganzo de Arriba', 'Villamanta', 'Anchuelo', 'Valdaracete', 'Ajalvir', 'Los Santos de la Humosa', 'Villamanrique de Tajo', 'Colmenar de Oreja', 'Villa del Prado', 'Fuentidueña de Tajo', 'Colmenar del Arroyo', 'Valdelaguna', 'Cubas de la Sagra', 'Valdeavero', 'Aldea del Fresno', 'Ribatejada', 'Torrelaguna', 'Batres', 'Pezuela de las Torres', 'Colmenarejo', 'Serranillos del Valle', 'Cobeña', 'Soto del Real', 'El Berrueco', 'Villanueva de Perales', 'Fresno de Torote - Serracines', 'Pozuelo del Rey', 'Pelayos de la Presa', 'La Cabrera', 'Nuevo Baztán', 'Perales de Tajuña', 'Villaconejos', 'Villarejo de Salvanés', 'Cadalso de los Vidrios', 'Santorcaz', 'Madarcos', 'Garganta de los Montes', 'Puentes Viejas', 'Torremocha de Jarama', 'Valdemanco', 'Braojos', 'Lozoyuela-navas-sieteiglesias', 'Piñuécar-gandullas', 'Valdepiélagos', 'Valverde de Alcalá', 'Villar del Olmo', 'Villamantilla', 'Horcajo de la Sierra', 'Gascones', 'Zarzalejo', 'Villavieja del Lozoya', 'Brea de Tajo', 'Estremera', 'Chapinería', 'Navarredonda', 'Patones', 'Ambite', 'Navalafuente', 'Lozoya', 'Canencia', 'Cabanillas de la Sierra', 'Buitrago del Lozoya', 'Fresno de Torote', 'Robregordo', 'Pinilla del Valle', 'Rascafría', 'La Hiruela', 'Montejo de la Sierra']

#### Ejercicio 05. ¿El dataset contiene valores nulos (NAs)? (★☆☆)

Imprima un booleano (`True` o `False`) para verificar si hay valores nulos seguido de las columnas que contiene el NAs.

In [2]:
# TODO
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';') 
print(ds.isnull().any())

Unnamed: 0          False
id_realEstates      False
isNew               False
realEstate_name      True
phone_realEstate     True
url_inmueble        False
rooms                True
bathrooms            True
surface              True
price               False
date                False
description          True
address             False
country             False
level1              False
level2              False
level3              False
level4               True
level5              False
level6               True
level7               True
level8               True
upperLevel          False
countryId           False
level1Id            False
level2Id            False
level3Id            False
level4Id            False
level5Id            False
level6Id            False
level7Id            False
level8Id            False
accuracy            False
latitude            False
longitude           False
zipCode              True
customZone           True
dtype: bool

#### Ejercicio 06. Elimina los valores nulos (NAs) del dataset, si aplica (★★☆)

Despues de eliminar los valores nulos, compara el tamaño del DataFrame antes y después de la eliminación.

In [4]:
# TODO
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';')
print("Largo del dataset antes de la depuracion", len(ds))
ds_depurado = ds.dropna(subset=['rooms', 'bathrooms'])
print("Largo del dataset despues de la depuracion", len(ds_depurado))

Largo del dataset antes de la depuracion 15335
Largo del dataset despues de la depuracion 14821

#### Ejercicio 07. ¿Cuál es la media de precios en la población de "Arroyomolinos (Madrid)"? (★★☆)

Imprima el valor obtenido de la columna level5.

In [7]:
# TODO
import pandas as pd
ds = pd.read_csv('assets/real_estate.csv', sep=';')
ds_arroyomolinos = ds[ds['level5']=='Arroyomolinos (Madrid)']
print(ds_arroyomolinos['price'].mean())

294541.59854014596

#### Ejercicio 08. Trazar el histograma de los precios para la población de "Arroyomolinos (Madrid)" y explica qué observas (★★☆)

Imprime el histograma de los precios y escribe en la celda del Markdown un breve análisis del trazado.

In [11]:
import matplotlib.pyplot as plt
import pandas as pd

# Trazar el histograma de precios
ds = pd.read_csv('assets/real_estate.csv', sep=';')
ds_arroyomolinos = ds[ds['level5']=='Arroyomolinos (Madrid)']
plt.hist(ds_arroyomolinos['price'])
plt.show()

AttributeError: module 'matplotlib' has no attribute 'colors'

Error in callback <function _enable_matplotlib_integration.<locals>.configure_once at 0x110cf5300> (for post_run_cell), with arguments args (<ExecutionResult object at 114fa7410, execution_count=11 error_before_exec=None error_in_exec=module 'matplotlib' has no attribute 'colors' info=<ExecutionInfo object at 114fa3ed0, raw_cell="import matplotlib.pyplot as plt
import pandas as p.." transformed_cell="import matplotlib.pyplot as plt
import pandas as p.." store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell:/Users/danielbarbosagarcia/Documents/Python/PythonGitDataScience/data-clean-up-pandas-for-beginners-project_dbg/project.es.ipynb#X43sZmlsZQ%3D%3D> result=None>,),kwargs {}:

AttributeError: module 'matplotlib' has no attribute 'backends'

**TODO: Markdown**. Para escribir aquí, haz doble clic en esta celda, elimina este contenido y coloca lo que quieras escribir. Luego ejecuta la celda.